### ISSUE TITLE
License correct?

### ISSUE THREAD

**Issue by kreutziger** [mercedesbenzio/stuttgart-food-travelers#2]
Should not we use some GNU license?

**Comment by activenode** [comment]
![image](https://user-images.githubusercontent.com/9058762/41354997-aee8aa4e-6f20-11e8-909b-c8b9e55cf30c.png)

**Comment by kreutziger** [comment]
[y, not?](https://brightcove04pmdo-a.akamaihd.net/4221396001/4221396001_5527490856001_5527487419001-vs.jpg?pubId=4221396001&videoId=5527487419001)

**Comment by activenode** [comment]
why not make a PR then m8 ?

**Comment by FranzSkuffka** [comment]
🍿
